### ISSUE TITLE
Wav64 24-bit BufferUnderflowException

### ISSUE THREAD

**Issue by Sciss** [Sciss/ScissLib#2]
In GitLab by @Sciss on Oct 6, 2020, 16:40

Wave64 mono 24-bit int 48 kHz 0.461 seconds. This was created in EisK using save-selection-as. Will have to find a clear way to reproduce:

```
java.nio.BufferUnderflowException
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:182)
	at de.sciss.synth.io.BufferReader$ThreeBytesLELike.read(BufferHandler.scala:305)
	at de.sciss.synth.io.BufferReader$ThreeBytesLELike.read$(BufferHandler.scala:296)
	at de.sciss.synth.io.BufferReader$ThreeBytesLE.read(BufferHandler.scala:155)
	at de.sciss.synth.io.AudioFile$Readable.read(AudioFile.scala:302)
```

**Comment by Sciss** [comment]
In GitLab by @Sciss on Oct 6, 2020, 17:20

mentioned in commit fc75d2d2d208f1608ae36ab511aec58aec271984
